### PR TITLE
Move PinNames.h to mbed-hal-k64f

### PR DESCRIPTION
**Pull request by bremoran**
The mbed-hal directory doesn't have an extraIncludes entry, so PinNames.h needs to move to mbed-hal-k64f

@salkinium

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by salkinium** [comment]
:+1:

**Comment by 0xc0170** [comment]
I thought you had an intention with mbed-hal folder there ;)

**Comment by 0xc0170** [comment]
You could write it in https://github.com/ARMmbed/mbed-hal-k64f/pull/19, I would rebased and merged. Will close the other one then.

**Comment by 0xc0170** [comment]
It seems you did not move the header, added a new one?

**Comment by miklis** [comment]
Build finished. No test results found.

**Pull request merged**
