### PR TITLE
Add crc

### PR DESCRIPTION
**Pull request by ansondtx20**
Better fix for UUID based MAC address. Must be coupled with the hal-frdm-k64f change set

https://github.com/ARMmbed/mbed-hal-frdm-k64f/pull/15

### CODE REVIEW

**Comment by 0xc0170** [comment]
Is this the same patch applied to k64f in mbed SDK?

**Comment by bremoran** [comment]
I don't see any k64f-specific code here. Could this be moved to core-util?

**Comment by hugovincent** [comment]
@bremoran +1 to putting any generic CRC code into core-util (or it's own module if that makes sense).

**Comment by kjbracey-arm** [comment]
I've been helping @hashnainvirk with a Nanostack Ethernet driver, so I've noticed something relevant.

K64F Ethernet drivers would need a CRC-32 routine anyway to do multicast filtering. Like many Ethernet devices, the K64F ENET filters based on a hash of the CRC-32 of the group address.

So it doesn't make sense to add  a different CRC-16 - if you're going to add any CRC routine, make sure it's the standard Ethernet CRC-32, and documented as such. Then it's more likely to be reused.

(And don't calculate the fast table at run-time - we're generally shorter of RAM than ROM, so blowing 256 bytes of it for a constant table doesn't seem sensible.)

**Comment by bremoran** [comment]
I did try taking a look through the k64f MAC driver, looking for CRC code and I wasn't able to find any. I believe that this is because it's implemented internally in the k64f MAC.

> 45.2.1.1 Ethernet MAC features
> * Implements the full 802.3 specification with preamble/SFD generation, frame
> padding generation, CRC generation and checking
> * CRC-32 checking at full speed with optional forwarding of the frame check sequence
> (FCS) field to the client
> * CRC-32 generation and append on transmit or forwarding of user application
> provided FCS selectable on a per-frame basis

**Comment by kjbracey-arm** [comment]
The hardware computes the CRC-32 for the frame. But incidentally it uses the computed CRC-32 of the first 6 bytes to do multicast (or additional unicast) filtering.

To program the filters you need to know the CRC-32 of the address you want to get. Our current k64f Ethernet driver doesn't have any multicast support, I believe, so lacks the code to program the filters.

**Comment by kjbracey-arm** [comment]
@hasnainvirk

**Comment by bremoran** [comment]
To speed this along, I'm going to merge this PR. I still think that CRC code should live in core-util, but having looked at this CRC code, it requires configuration in the header and, therefore is not general purpose.

**Comment by kjbracey-arm** [comment]
Fine. I want the MAC update patch even if just to get the multicast+local bits right, which the old code doesn't...

**Comment by kjbracey-arm** [comment]
(Still don't like the 256-byte RAM cost, but can address that later)

**Comment by bremoran** [comment]
@kjbracey-arm I would happily take FNV1 over CRC16, but this already works.

**Comment by kjbracey-arm** [comment]
As per my previous comments - I've changed my mind to shared CRC-32 being more sensible than either FNV-1 or CRC-16, as an Ethernet driver will quite likely want CRC-32 for multicast filtering. But this is fine for now.

My RAM nitpick is that this code builds a computation table into RAM, rather than holding it precomputed in flash or not using a table at all. Speed isn't an issue for this CRC application.

**Pull request merged**
