### PR TITLE
Include GeneratedPinNames.h from PinNames.h

### PR DESCRIPTION
**Pull request by bremoran**
This PR is the chip-side implementation of
https://github.com/ARMmbed/mbed-hal/pull/24

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by 0xc0170** [comment]
Shouldn't this be done in this repository where PinNames is https://github.com/ARMmbed/mbed-hal-frdm-k64f ? That's the platform repository.

**Comment by bremoran** [comment]
@0xc0170 No, this needs to live in mbed-hal-k64f.  It is purely a forwarder for chips that have yotta config enabled already.  The PinNames.h from mbed-hal-frdm-k64f has been deleted.

**Comment by 0xc0170** [comment]
It's still there : https://github.com/ARMmbed/mbed-hal-frdm-k64f/blob/master/mbed-hal-frdm-k64f/PinNames.h.Should be then deleted

**Pull request merged**
